annotation_task_name: "Object Detection"
task_name: "Object Detection"
task_description: "Draw bounding boxes around all objects of interest."
task_dir: "."
port: 8000

data_files:
  - "sample-data.json"

item_properties:
  id_key: "id"
  text_key: "image_url"
  image_key: image_url

annotation_schemes:
  - annotation_type: image_annotation
    name: objects
    description: "Draw boxes around objects"
    tools:
      - bbox
    labels:
      - "Person"
      - "Car"
      - "Dog"
      - "Cat"

output_annotation_dir: "output/"
output_annotation_format: "json"
