annotation_task_name: "Image Segmentation"
task_name: "Image Segmentation"
task_description: "Draw precise polygon boundaries around objects."
task_dir: "."
port: 8000

data_files:
  - "sample-data.json"

item_properties:
  id_key: "id"
  text_key: "image_url"
  image_key: image_url

annotation_schemes:
  - annotation_type: image_annotation
    name: segments
    description: "Draw polygons around each object"
    tools:
      - polygon
    labels:
      - "Person"
      - "Vehicle"
      - "Animal"
      - "Object"

output_annotation_dir: "output/"
output_annotation_format: "json"
